display_name: LocalChat
packager: Tienisto
packagerEmail: dev.tien.donam@gmail.com
url: https://github.com/WGHCWC/localsend_chat
buildArch: x86_64
license: MIT

icon: assets/img/logo-512.png

requires:
  - libappindicator
  - xdg-user-dirs

keywords:
  - Sharing
  - LAN
  - Files

generic_name: A LAN chat and file transfer app based on LocalSend
summary: Share files and chat locally with LocalChat
group: Applications/Utilities

categories:
  - GTK
  - FileTransfer
  - Utility

startup_notify: true
